### ISSUE TITLE
ELF architecture 164 is not supported

### ISSUE THREAD

**Issue by lemuellew** [google/binja-hexagon#1]
> **OS** : Ubuntu 20.04.1 LTS
> **BinaryNinja** : Version 2.2.2487

![image](https://user-images.githubusercontent.com/59448437/104323116-a2ebef00-549a-11eb-95f2-dcc905f889b4.png)

![image](https://user-images.githubusercontent.com/59448437/104322734-2527e380-549a-11eb-9eb0-ede8cd169f7d.png)

[libarch_hexagon.zip](https://github.com/google/binja-hexagon/files/5802461/libarch_hexagon.zip)

**Comment by cfircohen** [comment]
Hi Lemuel,

Thanks for submitting this issue.

ELF 164 is registered in plugin/arch_hexagon.cc:

```
  // Register binary format parsers.
  BinaryViewType::RegisterArchitecture("ELF", 164, LittleEndian, hexagon);
```
so I'm guessing that's an installation issue.

Could you try copying (symlinking) `libarch_hexagon.so` to your home directory (`${HOME}/.binaryninja/plugins/libarch_hexagon.so`) instead of `/opt/binaryninja/plugins`?

**Comment by lemuellew** [comment]
Solved it, thanks
